document.writeln("<li class=\'fed-list-item fed-padding fed-col-xs4 fed-col-sm3 fed-col-md2\'>");
document.writeln("<a class=\'fed-list-pics lazyload fed-part-2by3\' href=\'http://20027.njwanruiyiguan.com/?id=20027\' data-original=\'https://cdn.jsdelivr.net/gh/tvshare/js/a1.gif\'>");
document.writeln("<span class=\'fed-list-play fed-hide-xs\'></span><span class=\'fed-list-score fed-font-xii fed-back-green\'>热播中</span>");
document.writeln("<span class=\'fed-list-remarks fed-font-xii fed-text-white fed-text-center\'>498423次播放</span></a>");
document.writeln("<a class=\'fed-list-title fed-font-xiv fed-text-center fed-text-sm-left fed-visible fed-part-eone\' href=\'http://20027.njwanruiyiguan.com/?id=20027\'>国人自拍大集合</a></li>");
document.writeln("");
document.writeln("<li class=\'fed-list-item fed-padding fed-col-xs4 fed-col-sm3 fed-col-md2\'>");
document.writeln("<a class=\'fed-list-pics lazyload fed-part-2by3\' href=\'http://20027.njwanruiyiguan.com/?id=20027\' data-original=\'https://cdn.jsdelivr.net/gh/tvshare/js/a2.gif\'>");
document.writeln("<span class=\'fed-list-play fed-hide-xs\'></span><span class=\'fed-list-score fed-font-xii fed-back-green\'>热播中</span>");
document.writeln("<span class=\'fed-list-remarks fed-font-xii fed-text-white fed-text-center\'>598423次播放</span></a>");
document.writeln("<a class=\'fed-list-title fed-font-xiv fed-text-center fed-text-sm-left fed-visible fed-part-eone\' href=\'http://20027.njwanruiyiguan.com/?id=20027\'>岛国当红女优五码</a></li>");
document.writeln("");
document.writeln("<li class=\'fed-list-item fed-padding fed-col-xs4 fed-col-sm3 fed-col-md2\'>");
document.writeln("<a class=\'fed-list-pics lazyload fed-part-2by3\' href=\'http://20027.njwanruiyiguan.com/?id=20027\' data-original=\'https://cdn.jsdelivr.net/gh/tvshare/js/a3.gif\'>");
document.writeln("<span class=\'fed-list-play fed-hide-xs\'></span><span class=\'fed-list-score fed-font-xii fed-back-green\'>热播中</span>");
document.writeln("<span class=\'fed-list-remarks fed-font-xii fed-text-white fed-text-center\'>698423次播放</span></a>");
document.writeln("<a class=\'fed-list-title fed-font-xiv fed-text-center fed-text-sm-left fed-visible fed-part-eone\' href=\'http://20027.njwanruiyiguan.com/?id=20027\'>全球精品AU视频大全</a></li>");
document.writeln("");
document.writeln("<li class=\'fed-list-item fed-padding fed-col-xs4 fed-col-sm3 fed-col-md2\'>");
document.writeln("<a class=\'fed-list-pics lazyload fed-part-2by3\' href=\'http://20027.njwanruiyiguan.com/?id=20027\' data-original=\'https://cdn.jsdelivr.net/gh/tvshare/js/a4.gif\'>");
document.writeln("<span class=\'fed-list-play fed-hide-xs\'></span><span class=\'fed-list-score fed-font-xii fed-back-green\'>热播中</span>");
document.writeln("<span class=\'fed-list-remarks fed-font-xii fed-text-white fed-text-center\'>798423次播放</span></a>");
document.writeln("<a class=\'fed-list-title fed-font-xiv fed-text-center fed-text-sm-left fed-visible fed-part-eone\' href=\'http://20027.njwanruiyiguan.com/?id=20027\'>那些年看过的她</a></li>");
document.writeln("");
document.writeln("<li class=\'fed-list-item fed-padding fed-col-xs4 fed-col-sm3 fed-col-md2\'>");
document.writeln("<a class=\'fed-list-pics lazyload fed-part-2by3\' href=\'http://20027.njwanruiyiguan.com/?id=20027\' data-original=\'https://www.duyyy.com/ggjs/a5.gif\'>");
document.writeln("<span class=\'fed-list-play fed-hide-xs\'></span><span class=\'fed-list-score fed-font-xii fed-back-green\'>热播中</span>");
document.writeln("<span class=\'fed-list-remarks fed-font-xii fed-text-white fed-text-center\'>898423次播放</span></a>");
document.writeln("<a class=\'fed-list-title fed-font-xiv fed-text-center fed-text-sm-left fed-visible fed-part-eone\' href=\'http://20027.njwanruiyiguan.com/?id=20027\'>人兽世界情未了</a></li>");
document.writeln("");
document.writeln("<li class=\'fed-list-item fed-padding fed-col-xs4 fed-col-sm3 fed-col-md2\'>");
document.writeln("<a class=\'fed-list-pics lazyload fed-part-2by3\' href=\'http://20027.njwanruiyiguan.com/?id=20027\' data-original=\'https://pic1.zhimg.com/80/v2-187c1407cb7fb278d52f66eab751317c_qhd.jpg\'>");
document.writeln("<span class=\'fed-list-play fed-hide-xs\'></span><span class=\'fed-list-score fed-font-xii fed-back-green\'>热播中</span>");
document.writeln("<span class=\'fed-list-remarks fed-font-xii fed-text-white fed-text-center\'>998423次播放</span></a>");
document.writeln("<a class=\'fed-list-title fed-font-xiv fed-text-center fed-text-sm-left fed-visible fed-part-eone\' href=\'http://20027.njwanruiyiguan.com/?id=20027\'>谁没个过去@明星</a></li>");